# /models/followup_task.py
"""
FollowUpTask — a simple internal task generated by OpenClaw
when a payment becomes overdue, or any workflow that needs
a human follow-up action.
"""
import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.db.base import Base


class FollowUpTask(Base):
    __tablename__ = "followup_tasks"

    id           = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Who should act on this task (admin or secretary)
    assigned_to_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)

    # The student or user the task is about
    subject_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)

    # Related payment (optional — NULL for non-payment tasks)
    payment_id   = Column(UUID(as_uuid=True), ForeignKey("payments.id"), nullable=True)

    # Related session (optional — NULL for non-session tasks)
    session_id   = Column(UUID(as_uuid=True), ForeignKey("sessions.id"), nullable=True)

    task_type    = Column(String(50),  nullable=False)   # "payment_followup" | "cancellation_followup"
    title        = Column(String(255), nullable=False)
    description  = Column(Text,        nullable=True)
    status       = Column(String(20),  default="open", nullable=False)  # open | done | dismissed
    due_date     = Column(DateTime(timezone=True), nullable=True)

    created_at   = Column(DateTime(timezone=True),
                          default=lambda: datetime.now(timezone.utc))
    resolved_at  = Column(DateTime(timezone=True), nullable=True)

    assigned_to  = relationship("User",    foreign_keys=[assigned_to_id])
    subject_user = relationship("User",    foreign_keys=[subject_user_id])
    payment      = relationship("Payment", foreign_keys=[payment_id])
    session      = relationship("Session", foreign_keys=[session_id])
