"""add rejection_reason to sessions

Revision ID: a56002cf06d5
Revises: 857ae1a69487
Create Date: 2026-05-04 12:02:09.102601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56002cf06d5'
down_revision: Union[str, Sequence[str], None] = '857ae1a69487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'rejection_reason')
    # ### end Alembic commands ###
