"""add telegram fields to users

Revision ID: ae879550500c
Revises: ca7313d28c9f
Create Date: 2026-04-13 23:16:14.075521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae879550500c'
down_revision: Union[str, Sequence[str], None] = 'ca7313d28c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('telegram_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('telegram_otp_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_otp_expires')
    op.drop_column('users', 'telegram_otp')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
